#!/usr/bin/env bash
# update Brew formulae
TAG=$(git describe)
COMMIT=$(git log --pretty=%H -1)

if type brew >/dev/null 2>&1 ; then
    info-text "Updating Homebrew formulae..."
    brew bump-formula-pr --no-audit --tag=${TAG} --revision=${COMMIT} aws-creds
else
    error-text "brew binary is not available."
    error-text "Please make a manual formulae update."
    cat <<MESSAGE
Instructions:

    open       https://github.com/bees-hive/homebrew-hive/blob/main/Formula/aws-creds.rb#L4
    update
        git tag:     ${TAG}
        git commit:  ${COMMIT}
MESSAGE
fi
# add GitHub release
open https://github.com/bees-hive/aws-creds/releases/new
