#!/usr/bin/env bash
set -o errexit
set -o pipefail
cd "$(git rev-parse --show-toplevel)"
# update Brew formulae
TAG=$(git describe)
COMMIT=$(git log --pretty=%H -1)

if type brew >/dev/null 2>&1; then
  echo "Updating Homebrew formulae..."
  brew bump-formula-pr --no-audit --tag="${TAG}" --revision="${COMMIT}" aws-creds
else
  echo "'brew' binary is not available."
  echo "Please make a manual formulae update."
  cat <<MESSAGE
Instructions:

    open       https://github.com/bees-hive/homebrew-hive/blob/main/Formula/aws-creds.rb#L4
    update
        git tag:     ${TAG}
        git commit:  ${COMMIT}
MESSAGE
fi
# add GitHub release
# shellcheck disable=SC2046 # Quote this to prevent word splitt...
git-elegant show-release-notes smart $(git tag | tail -2 | head -1) $(git tag | tail -1) | pbcopy
echo "Release notes are in the clipboard."
sleep 2
open https://github.com/bees-hive/aws-creds/releases/new
