#!/usr/bin/env bash
# This script invokes ahead of the 'save-work' execution.
set -o errexit
set -o pipefail
cd "$(git rev-parse --show-toplevel)"

which -s ruff || (echo "ruff is not installed" && exit 1)
ruff check --config line-length=120 --fix aws-creds.py ||
  ruff check --config line-length=120 --add-noqa aws-creds.py
ruff format --config line-length=120 aws-creds.py
