#!/usr/bin/env bash
# This script invokes ahead of the 'save-work' execution.
set -o errexit
set -o pipefail
cd "$(git rev-parse --show-toplevel)"

echo "Verifying 'aws-creds.py'..."
which -s ruff || (echo "ruff is not installed" && exit 1)
ruff check --config line-length=120 --fix aws-creds.py ||
  ruff check --config line-length=120 --add-noqa aws-creds.py
ruff format --config line-length=120 aws-creds.py

echo "Update __version__ in 'aws-creds.py'..."
# shellcheck disable=SC2046 # Quote this to prevent word splitt...
latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
new_version="${latest_tag}+$(date "+%Y%m%d-%H%M%S")"
if [[ $OSTYPE == "darwin"* ]]; then
  # macOS system
  sed -i '' "s/__version__ = .*/__version__ = \"$new_version\"/" aws-creds.py
else
  sed -i "s/__version__ = .*/__version__ = \"$new_version\"/" aws-creds.py
fi
python aws-creds.py --version

echo "Verifying 'install.sh'..."
if test "$USER" != "extsoft"; then
  echo "Local installation has been disabled for the '$USER' user."
  echo "To enable it, please update '.workflows/save-work-after' script."
else
  bash install.sh
fi
