#!/usr/bin/env bash
# This workflow installs the new updated script after every commit.
set -o errexit
set -o pipefail
if test "$USER" != "extsoft"; then
  echo "Local installation has been disabled for the '$USER' user."
  echo "To enable it, please update '.workflows/save-work-after' script."
  exit
fi
cd "$(git rev-parse --show-toplevel)"
destination="$HOME/.local/bin"
mkdir -p "${destination}"
install -v -m 755 aws-creds.py "${destination}/aws-creds"
